### ISSUE TITLE
Remove h5py dependencies

### ISSUE THREAD

**Issue by chadfreer** [SUEPPhysics/SUEPCoffea_dask#101]
remove pip install from the condor jobs:
https://github.com/SUEPPhysics/SUEPCoffea_dask/blob/master/kraken_run.py#L29

Dependencies in the ML:
https://github.com/SUEPPhysics/SUEPCoffea_dask/blob/master/workflows/ML_coffea.py#L12

**Comment by lucalavezzo** [comment]
Might want to keep these, it's a good file format for what we want. We should see if we can get it added into the coffea singularity.

**Comment by chadfreer** [comment]
h5py added into coffea singularity: https://github.com/CoffeaTeam/docker-coffea-base/pull/79
