### ISSUE TITLE
Improve plotting: make_plots.py

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#108]
- make_plots.py works and is pretty automatic, but it's not robust at all, as it depends on the column names of the DataFrame and of the hsistograms to be named precisely in certain ways
- it's also very hard for anyone to understand what's going on, making it hard to make sure that it's working properly
- needs major conceptual simplification

**Comment by lucalavezzo** [comment]
This is being addressed in #119

**Comment by chadfreer** [comment]
Addressed in https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/123
