### ISSUE TITLE
remove torch dependencies from scripts that don't need them

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#109]
Since we pushed all the ML utils in ML_utils.py, the ML_coffea.py script, which converts the miniAOD to training samples and which uses the ML_utils.py, is forced to import torch and other dependencies that it doesn't need, and which are quite annoying to install.
Would be nice to remove this dependency for ML_coffea.py, as well as any other scripts that don't explicitly need it.

**Comment by chadfreer** [comment]
Fixed by https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/128
