### ISSUE TITLE
Barebones CI

### ISSUE THREAD

**Issue by chrispap95** [SUEPPhysics/SUEPCoffea_dask#118]
How do you guys feel about introducing a very simple CI that applies code styling and formatting?
@chadfreer @lucalavezzo

**Comment by chadfreer** [comment]
I think this is probably a good idea at this point. 

Whatever is applied in this repo should probably also be applied in the SUEPLimits (maybe others as well) repos.

@chrispap95 Do you want me to assign this to you?

**Comment by chrispap95** [comment]
Sure. I can do this tomorrow morning.
