### ISSUE TITLE
cutflows

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#124]
Figure out what to do with this. 
1. keep it, and move it to some folder additional_tools/
2. remove it, and the counts after each cutflow in our normal analyzer

**Comment by chadfreer** [comment]
I moved the cutflows into a folder in additional_tools in order to reduce clutter. See https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/136

We can revisit this if we want a more sophisticated solution but for now this is fine
