### ISSUE TITLE
systematic plotting notebooks

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#125]
make simple plotting notebooks, one per systematic, and put them in the plotting/CMS_corrections. There are already some bits of this in the plotting/plot.ipynb that can be used.

**Comment by chadfreer** [comment]
Put them in additional_tools/systematic_plots:
https://github.com/SUEPPhysics/SUEPCoffea_dask/tree/master/additional_tools/systematic_plots

**Comment by chadfreer** [comment]
PU notebook added in https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/134
