### ISSUE TITLE
Closure test with metric

### ISSUE THREAD

**Issue by chadfreer** [SUEPPhysics/SUEPCoffea_dask#141]
Create notebook to make closure plots including a metric to quantify improvement for the extended ABCD method.

**Comment by lucalavezzo** [comment]
Addressed in #147 . Do we need a separate notebook for ABCD? All that code already present in plot.ipynb. For now, I've copied it and put it in its own notebook: plotting/ABCD.ipynb

**Comment by lucalavezzo** [comment]
I decided it's best to keep it in different notebooks. Will close this when I merge the pull
