### ISSUE TITLE
Check efficiency on signal of the quality filters

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#236]

**Comment by jreic** [comment]
So far, we've seen high efficiency, as per @cmauceri's most recent update in https://indico.cern.ch/event/1346011/contributions/5666420/attachments/2753283/4793312/suep_updates_11-14.pdf (and I think there were more recent plots that were in the workshop's backup slides).

**Comment by lucalavezzo** [comment]
We have validated this in the framework as well, where we see efficiencies of 99%. Closing this.
