### ISSUE TITLE
Add MET to WH producer

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#240]

**Comment by chadfreer** [comment]
Resolved in https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/246

**Comment by jreic** [comment]
Hi @chadfreer, we should think about adding DeepMET as well.

**Comment by jreic** [comment]
Maybe I am wrong about DeepMET... At least in the [Nano v9 UL18 documentation](https://cms-nanoaod-integration.web.cern.ch/autoDoc/NanoAODv9/2018UL/doc_TTToSemiLeptonic_TuneCP5_13TeV-powheg-pythia8_RunIISummer20UL18NanoAODv9-106X_upgrade2018_realistic_v16_L1v1-v1.html), we only store

```
DeepMETResolutionTune_phi
DeepMETResolutionTune_pt
DeepMETResponseTune_phi
DeepMETResponseTune_pt
```

which seems like it would be insufficient for systematic variations? I haven't followed DeepMET very closely though. Mainly thought about it in the context of the mW analysis.

**Comment by chadfreer** [comment]
DeepMET is not ideal for this analysis. Will close this issue
