### ISSUE TITLE
WH Central Request of samples

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#241]

**Comment by jreic** [comment]
Private signal samples are available on lxplus at `/eos/user/j/jreicher/SUEP/WH_private_signals/merged/` and on subMIT at `/data/submit/jreicher/SUEP/WH_private_signals/merged`.

We should work on adding these into file lists (and can move them to other directories if it makes life easier for any assumed filepaths in the existing framework). Working on the central request is next.

**Comment by jreic** [comment]
Submitted in https://gitlab.cern.ch/cms-exo-mci/EXO-MCsampleRequests/-/merge_requests/205

**Comment by jreic** [comment]
We can follow the request on GrASP here: https://cms-pdmv-prod.web.cern.ch/grasp/samples?tags=WSUEP

**Comment by jreic** [comment]
Done! All available at

`dasgoclient -query "dataset dataset=/WSUEP*/*/MINIAODSIM"`

and have been turned into Nanos under

`/store/user/paus/nanosu/A02//WSUEP*` (and are fully done as per https://ppc.mit.edu/Kraken/reviewd/nanosu/A02/status-nano.html)
