### ISSUE TITLE
Improve make_plots.py

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#254]
- [ ] The configurations should come from a yaml file and be taken as an input, hardcoding as we do now is not sustainable.
- [x] Consider adding a --channel [WH, ggF] (had to add one to get it to run for WH but maybe we can do it all from the configuration yaml?)
- [x] Come up with a better solution for the output histograms. Maybe move to a separate file?
- [x] Add function to calculate a new column of the dataframe using as inputs other columns. e.g. to calculate delta gen mass and reco mass

**Comment by pmlugato** [comment]
figure out which systematics are needed for WH, there is some repeated code in 'calculate systematic', and only if/else for scouting or not scouting.

**Comment by pmlugato** [comment]
(for now everything the same but no triggerSF weights)

**Comment by lucalavezzo** [comment]
2 and 3 addressed in #279

**Comment by lucalavezzo** [comment]
I think for now we leave 1 as is, it's not ideal, but I don't want to change too many things all at once, it will just confuse everyone. We already moved where hists are defined in this PR. If it becomes a requested feature, or a problem in the future, we can revisit.
