### ISSUE TITLE
Variables to add to hdf5's output dataframe for WH

### ISSUE THREAD

**Issue by jreic** [SUEPPhysics/SUEPCoffea_dask#257]
Mostly items that came up during the WH meeting on October 25th:

- [x] add information pertaining to jets (e.g. kinematics, btagging scores, quark/gluon info), for a variety of studies (including control regions)
- [x] add lepton ID, isolation, impact parameter for the purpose of optimizing our lepton selection
- [x] do we want to add pre-computed mT variables into the dataframes, or simple helper functions for post-computing them? 
- [x] rename "TopPT" to "HighestPT" to avoid confusion with the top quark!
- [x] And for "TopPT" -> "HighestPT": update any plotting scripts to do the same (want to coordinate with any of the parallel branches where plotting improvements are in the works)

I'll volunteer to work on the lepton variables, but if anyone else wants to tackle any of these others, please let me know!

**Comment by jreic** [comment]
Marking off a few that are ready locally--will push once I wrap up the rest + test.

**Comment by pmlugato** [comment]
mT is pre-computed and stored in dataframe -- will create PR and merge once current version of master is tagged!

**Comment by jreic** [comment]
Lepton variables and TopPT added into https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/276, which is a PR into the WH_pietro branch for the time being.
(and I tested that it seems to work on a signal sample and a single QCD file. I went a bit overkill with the number of isolation variants, but better to have them than not. I'm sure we'll drop them down the road.)

**Comment by lucalavezzo** [comment]
Done in #288
