### ISSUE TITLE
Infrastructure to avoid double counting events in data

### ISSUE THREAD

**Issue by jreic** [SUEPPhysics/SUEPCoffea_dask#260]
For instance, if an event fires both SingleElectron and SingleMuon, we don't want to double count it. Probably matters most in an e+mu control region, since our single lepton search regions should be orthogonal by construction.

Easiest thing will be to assign events to (say) SingleMuon if it fires both triggers, and discard it from the other. It's a small detail.

**Comment by chadfreer** [comment]
resolved in https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/322
