### ISSUE TITLE
Fixes before merging WH_pietro branch into master

### ISSUE THREAD

**Issue by jreic** [SUEPPhysics/SUEPCoffea_dask#278]
Following https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/276, some suggested fixes were made, which we will take care of before merging into master:

- [ ] Store fewer variables to save on space: https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/276#discussion_r1425937863
- [ ] Use vector's deltaphi: https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/276#discussion_r1425939280 (and all other instances of deltaphi)
- [ ] Remove a no-longer-needed line: https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/276#discussion_r1426810475

**Comment by lucalavezzo** [comment]
This branch has now been merged into master.
