### ISSUE TITLE
Study tight lepton ID

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#297]
Seems like the most promising option for reducing the QCD backgrounds.

**Comment by jreic** [comment]
Slides: https://indico.cern.ch/event/1378651/contributions/5794497/attachments/2795197/4875761/2024-02-06%20SUEP%20WH%20Lepton%20ID%20Study.pdf

PR: https://github.com/SUEPPhysics/SUEPCoffea_dask/pull/305

**Comment by jreic** [comment]
Merged in, closing. And letting @pmlugato know that it is in place for our next round of ntuple production.
