### ISSUE TITLE
Functions to make cutflow tables / plots

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#298]
Now that we have cutflows integrated up until the loader(), it would be nice to have some small function to make tables and plots. Should be minor, I already put something like this together for the presentation last week.

**Comment by jreic** [comment]
I had exactly the same thought earlier today! We should also make sure to keep track of our cutflows in a weighted manner, because I believe we currently only track them in terms of raw MC events. Both ways could actually come in handy.

**Comment by lucalavezzo** [comment]
So in each .root file we store as you say the raw MC count, but we should also store the xsec and eventweights so it should be easy to switch between, but I will double check!
