### ISSUE TITLE
DeepMET

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#299]
DeepMET has been mentioned as an option for us. We should study it. Do we have it the nanos?

**Comment by jreic** [comment]
We have these in Nanov9:

```
DeepMETResolutionTune_phi	Float_t	DeepmET ResolutionTune phi
DeepMETResolutionTune_pt	Float_t	DeepMET ResolutionTune pt
DeepMETResponseTune_phi	Float_t	DeepMET ResponseTune phi
DeepMETResponseTune_pt	Float_t	DeepMET ResponseTune pt
```

though I do remember it being pointed out that mW can rely on DeepMET given the low pileup.

**Comment by jreic** [comment]
I think our conclusion is to avoid it. Should we close?

**Comment by chadfreer** [comment]
Yes we can close this.
