### ISSUE TITLE
New variables: delta_phi(SUEP, W), balancing variable

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#300]
Mentioned in MIT group meeting as possible selection variables.

**Comment by jreic** [comment]
Is "balancing variable" something different from dphi? e.g. one could think of momentum ratios (as ZH has effectively studied, by changing pTZ requirements).

**Comment by lucalavezzo** [comment]
Yes sorry, I meant the momentum ratio (pT SUEP - pT W) / pT SUEP or pT SUEP / pT W or something like that

**Comment by lucalavezzo** [comment]
During meeting, discussed checking them after upper mT cut.

**Comment by lucalavezzo** [comment]
These have been added, #301 tracks progress in optimizing.
