### ISSUE TITLE
Optimize selections (W pT/mT, MET, deltaPhi, balancing variable, ...)

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#301]
For now we set both to 50 GeV, but should optimize them. The question is really how do we want to evaluate that. A significance scan across all backgrounds?

**Comment by lucalavezzo** [comment]
yea agreed, we will do this after the b jets and the lepton selection are defined. Thank you!

**Comment by jreic** [comment]
Should also pick a figure of merit to optimize with: https://twiki.cern.ch/twiki/bin/view/CMS/FigureOfMerit

The Asimov significance is pretty easy math, and approximates S/sqrt(B) (which is good for optimizing for discovery) without breaking down for B->0 (though that isn't actually an issue for us when looking inclusively in nConst)

**Comment by lucalavezzo** [comment]
Seems like a good choice. The only last question I had for this was whether to check the yields for everything that passes our selections, or all the selections plus the SR ones as defined by the ABCD regions, i.e. with some cut on nconst and cluster pT.

**Comment by jreic** [comment]
Good question! cluster pT > 60 GeV is already built in to our ntuples, so I'm not sure if you mean a tighter one or a lead (AK4) jet pT requirement. Ultimately, I think we do want to see that we can extract signal from the background in that region--maybe there is still some wiggle room on the exact SR defintion still, so I could see pros and cons with either choice. To make life harder, I would do it both ways and see if the optimal choices even differ.

**Comment by lucalavezzo** [comment]
I just mean that, like the ZH defines a SR for the ABCD background, labeled A below, we will likely have some SR defined in the same way, and the sensitivity metric we choose should be evaluated there more heavily than e.g. in B2 or E1.

![image](https://github.com/SUEPPhysics/SUEPCoffea_dask/assets/38077849/3b47ed88-5d84-4ed5-86aa-b951048bd76e)

**Comment by jreic** [comment]
Right--A is where it matters the most, so checking the sensitivity there is logical, and is probably where we should do the optimization. I was partly thinking that we wanted to optimize Nconst and jet pT cuts as well, but we should probably keep those aligned with ZH, now that I think about it more. So let's plan to optimize these MET/pT/mT cuts based on region A, but I think a check of the significances when using the full ABCD plane is still worthwhile. If the optimal significance is very different in the full ABCD region vs. in the A region, there could be some correlation that we are learning about.

**Comment by lucalavezzo** [comment]
Just for reference, we agreed during meeting not to over-engineer this. We will check a couple of representative samples, and optimize wrt those.

**Comment by lucalavezzo** [comment]
Currently studying selections on:
- W mT
- W pT
- MET pT
- deltaPhi between [lepton, MET, SUEP, minDeltaJetMET, photon, balancing variable W/SUEP pT]

The idea at the moment is to pick some physics-inspired values as benchmark, and then try to optimize a bit on those. Don't over-tune to any signal sample.

**Comment by lucalavezzo** [comment]
We have settled on some selections for now; if we need to optimize further, we will.
