### ISSUE TITLE
Refine B jet selection

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#302]
Options discussed:
1. 0 tight jets
2. 0 tight jets and < 2 loose jets
3. 0 loose jets
Should explore these and possibly others by checking the yield for each background and signal. Easy thing would be to run all of them and make a cutflow table for each.

**Comment by jreic** [comment]
Using nTight == 0 && nLoose < 2 in the SR looked pretty promising in https://indico.cern.ch/event/1378651/contributions/5794497/attachments/2795197/4875776/SUEP_WH_2_6.pdf. @pmlugato, should we close this?

**Comment by lucalavezzo** [comment]
Let's close this when we move it to the ntuplemaker. Pietro I think wants to check the cutflow tables before finalizing that, I will leave it up to the next PR to add it in.

**Comment by lucalavezzo** [comment]
We discussed adding this to make_hists.py rather than ntuples, so we can invert the selection on the fly for CRs.
