### ISSUE TITLE
LO vs. NLO W gen pT Studies

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#311]
We need to get a better handle on and disentangle the differences coming from the LO vs NLO simulations, and the differences that are inherent between the two samples.

It was proposed to study a NLO VH sample as a proxy for signal, and compare it to WJets --> look at W pT, delta_phi(SUEP, W).

**Comment by lucalavezzo** [comment]
Compared LHE_Vpt for VH and WH with GenPart_status == 22 for WSUEP: agreement looks good across all of them! probably don't need a correction.

**Comment by jreic** [comment]
(may be useful to put these plots directly in the (currently-empty) AN before too long, so we don't lose them!)

**Comment by lucalavezzo** [comment]
We can make an issue regarding documentation separately, the studies have shown good agreement in WH SUEP, WH and VH in the W gen pT.
