### ISSUE TITLE
Split central samples

### ISSUE THREAD

**Issue by lucalavezzo** [SUEPPhysics/SUEPCoffea_dask#315]
After testing some ideas to split them at the ntuple / hists level, we are reverting to the use of Carlos' splitTress.py [1]. The current idea is to modify this script to run over the samples on the MIT T2 and just stage the output ourselves on T2 as well.

[1] - https://github.com/cericeci/SUEPNano/blob/ul/test/splitTrees.py

**Comment by jreic** [comment]
Done in #326
