### ISSUE TITLE
Add check proxy function

### ISSUE THREAD

**Issue by chadfreer** [SUEPPhysics/SUEPCoffea_dask#66]
Add a function to check the proxy. Already in kraken [1] but can be moved to plot_utils. 

This option should then be added to make_plots and merge_plots. For kraken the proxy needs to be made available in home so that condor has access to is

[1]
https://github.com/SUEPPhysics/SUEPCoffea_dask/blob/master/kraken_run.py#L100-L113

**Comment by lucalavezzo** [comment]
See #69

**Comment by lucalavezzo** [comment]
- function check_proxy was added to plot_utils
- function is called from kraken_run.py and multithread.py

**Comment by chadfreer** [comment]
merged
